# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# platform :android do

# before_all do
#     ENV["FIREBASE_CI_TOKEN"] = "1//03v1Pl0r7AWorCgYIARAAGAMSNwF-L9IrkrlQOtK6f3EJkBDRWEPTvMLS3viAeKBidd2KRfo_Q6SYojKulLbeWZxo57ialwcxD30"
#     ENV["FIREBASE_APP_ID"] = "1:829346185170:android:af75c842b479f438e0d20b"
#   end

#  desc "Generate build and upload to firebase"
#  lane :build do
#    gradle(
#      task: "assemble",
#      build_type: "Staging"
#    )
#    firebase_app_distribution(
#      app: ENV["FIREBASE_APP_ID"],
#      release_notes_file: "releaseNotes.txt",
#      groups: "Internal",
#      firebase_cli_token: ENV['FIREBASE_CI_TOKEN'],
#      debug: false
#    )
#   end
# end

platform :android do

 desc "Generate build and upload to firebase"
 lane :build do
   gradle(
     task: "assemble",
     build_type: ENV['BUILD_TYPE'],
   )
   firebase_app_distribution(
     app: ENV["FIREBASE_APP_ID"],
     release_notes_file: "releaseNotes.txt",
     groups: "Internal",
     firebase_cli_token: ENV['FIREBASE_CI_TOKEN'],
     debug: false
   )
  end
end
