# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "clean"
lane :clean do
  gradle(
     task: "clean"
   )
end

platform :android do
 desc "Generate build and upload to firebase"
 lane :build do
   gradle(
      task: "clean"
   )
   gradle(
     task: "assemble",
     build_type: ENV["BUILD_TYPE"],
   )
   firebase_app_distribution(
     app: ENV["FIREBASE_APP_ID"],
     release_notes_file: "releaseNotes.txt",
     groups: "Internal",
     firebase_cli_token: ENV["FIREBASE_CI_TOKEN"],
     debug: false
   )
  end
end